---
- name: Jicofo user
  include_tasks: create_xmpp_user.yml
  vars:
    xmpp_user: "{{ jicofo_user }}"
    xmpp_pass: "{{ jicofo_pass }}"
    xmpp_domain: "auth.{{ meet_domain }}"

- name: Videobridge users
  include_tasks: create_xmpp_user.yml
  vars:
    xmpp_user: "{{ hostvars[item].videobridge_user }}"
    xmpp_pass: "{{ hostvars[item].videobridge_pass }}"
    xmpp_domain: "auth.{{ meet_domain }}"
  loop: "{{ groups['videobridges'] }}"

- name: Jibri users in auth domain
  include_tasks: create_xmpp_user.yml
  vars:
    xmpp_user: "{{ hostvars[item].jibri_user }}"
    xmpp_pass: "{{ hostvars[item].jibri_pass }}"
    xmpp_domain: "auth.{{ meet_domain }}"
  loop: "{{ groups['jibris'] }}"

- name: Jibri users in recorder domain
  include_tasks: create_xmpp_user.yml
  vars:
    xmpp_user: "{{ hostvars[item].jibri_user }}"
    xmpp_pass: "{{ hostvars[item].jibri_pass }}"
    xmpp_domain: "recorder.{{ meet_domain }}"
  loop: "{{ groups['jibris'] }}"

- name: Prometheus exporter user
  include_tasks: create_xmpp_user.yml
  vars:
    xmpp_user: "{{ exporter_xmpp_user }}"
    xmpp_pass: "{{ exporter_xmpp_pass }}"
    xmpp_domain: "auth.{{ meet_domain }}"
